CREATE TABLE [dbo].[Bane](
	[BaneNr] [smallint] NOT NULL,
	[Banenavn] [nvarchar](10) NULL,
 CONSTRAINT [PK_Bane] PRIMARY KEY CLUSTERED 
(
	[BaneNr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]